export const GENRES = {
  27: 'genre.horror' as const,
  9648: 'genre.mystery' as const,
  28: 'genre.action' as const,
  16: 'genre.animation' as const,
  35: 'genre.comedy' as const,
  12: 'genre.adventure' as const,
  80: 'genre.crime' as const,
  99: 'genre.documentary' as const,
  18: 'genre.drama' as const,
  10751: 'genre.family' as const,
  14: 'genre.fantasy' as const,
  36: 'genre.history' as const,
  10402: 'genre.music' as const,
  10749: 'genre.romance' as const,
  878: 'genre.science' as const,
  10770: 'genre.tv' as const,
  53: 'genre.thriller' as const,
  10752: 'genre.war' as const,
  37: 'genre.western' as const,
}
